spring:
  config:
    activate:
      on-profile: development

environment: development
minPassword : 1
minUser : 1
maxUser : 100
maxPassword : 100

---
spring:
  config:
    activate:
      on-profile: production

environment: production
minPassword : 12
minUser : 6
maxUser : 20
maxPassword : 20